#!/bin/bash -e

tag=$1

# Build Docker image
docker_image="096040694364.dkr.ecr.eu-west-1.amazonaws.com/sbires:${tag}"
docker pull "${docker_image}" 2>/dev/null || true
docker build -t "${docker_image}" .

# Push Docker image to ECR
docker push "${docker_image}"
