#!/bin/bash -e

tag=$1

# install aws cli
pip install --user --upgrade pip
pip install --user awscli
export PATH=$PATH:$HOME/.local/bin

# login ecr
eval $(aws ecr get-login --region eu-west-1 --no-include-email)

# Build Docker image
docker_image="096040694364.dkr.ecr.eu-west-1.amazonaws.com/sbires:${tag}"
docker pull "${docker_image}" 2>/dev/null || true
docker build -t "${docker_image}" .

# Push Docker image to ECR
docker push "${docker_image}"